// Generated by gencpp from file inz/Formation.msg
// DO NOT EDIT!


#ifndef INZ_MESSAGE_FORMATION_H
#define INZ_MESSAGE_FORMATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace inz
{
template <class ContainerAllocator>
struct Formation_
{
  typedef Formation_<ContainerAllocator> Type;

  Formation_()
    : Lx(0.0)
    , Ly(0.0)
    , L(0.0)  {
    }
  Formation_(const ContainerAllocator& _alloc)
    : Lx(0.0)
    , Ly(0.0)
    , L(0.0)  {
  (void)_alloc;
    }



   typedef float _Lx_type;
  _Lx_type Lx;

   typedef float _Ly_type;
  _Ly_type Ly;

   typedef float _L_type;
  _L_type L;




  typedef boost::shared_ptr< ::inz::Formation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::inz::Formation_<ContainerAllocator> const> ConstPtr;

}; // struct Formation_

typedef ::inz::Formation_<std::allocator<void> > Formation;

typedef boost::shared_ptr< ::inz::Formation > FormationPtr;
typedef boost::shared_ptr< ::inz::Formation const> FormationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::inz::Formation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::inz::Formation_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace inz

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'inz': ['/home/leszek/armulti_simulator_ws/src/inz/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::inz::Formation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::inz::Formation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inz::Formation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inz::Formation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inz::Formation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inz::Formation_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::inz::Formation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d31db8d8681c59a19527284d3d5b77c3";
  }

  static const char* value(const ::inz::Formation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd31db8d8681c59a1ULL;
  static const uint64_t static_value2 = 0x9527284d3d5b77c3ULL;
};

template<class ContainerAllocator>
struct DataType< ::inz::Formation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "inz/Formation";
  }

  static const char* value(const ::inz::Formation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::inz::Formation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 Lx\n\
float32 Ly\n\
float32 L\n\
";
  }

  static const char* value(const ::inz::Formation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::inz::Formation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Lx);
      stream.next(m.Ly);
      stream.next(m.L);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Formation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::inz::Formation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::inz::Formation_<ContainerAllocator>& v)
  {
    s << indent << "Lx: ";
    Printer<float>::stream(s, indent + "  ", v.Lx);
    s << indent << "Ly: ";
    Printer<float>::stream(s, indent + "  ", v.Ly);
    s << indent << "L: ";
    Printer<float>::stream(s, indent + "  ", v.L);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INZ_MESSAGE_FORMATION_H
